In [389]:
import sys
print(sys.executable)

c:\Users\majom\OneDrive\Desktop\Python Libraries\Pandas\venv\Scripts\python.exe

In [390]:
import pandas as pd

## Pandas Series

In [391]:
s = pd.Series([10,20,30,40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [392]:
fruits = pd.Series(["Apple","Banana","Mango"])
print(fruits)

0     Apple
1    Banana
2     Mango
dtype: str

In [393]:
marks = pd.Series([91.5, 82.0, 76.25])

print(marks)

0    91.50
1    82.00
2    76.25
dtype: float64

In [394]:
passed = pd.Series([True, False, True])

print(passed)

0     True
1    False
2     True
dtype: bool

### Creating a Series with Custom Index

In [395]:
students = pd.Series(
    [85, 90, 78],
    index=["Ali", "Sara", "John"]
)

print(students)

Ali     85
Sara    90
John    78
dtype: int64

### Accessing Values

In [396]:
numbers = pd.Series([10, 20, 30, 40])

print(numbers[0])

10

In [397]:
students = pd.Series(
    [85, 90, 78],
    index=["Ali", "Sara", "John"]
)

print(students["Sara"])

90

### Slicing a Series

In [398]:
numbers = pd.Series([10, 20, 30, 40, 50])

In [399]:
print(numbers[:3])

0    10
1    20
2    30
dtype: int64

### Series Attributes

In [400]:
numbers.dtype

dtype('int64')

In [401]:
numbers.size

5

In [402]:
numbers.shape

(5,)

In [403]:
numbers.values

array([10, 20, 30, 40, 50])

In [404]:
numbers.index

RangeIndex(start=0, stop=5, step=1)

In [405]:
numbers.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [406]:
numbers.head(2)

0    10
1    20
dtype: int64

In [407]:
numbers.tail()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [408]:
numbers.tail(2)

3    40
4    50
dtype: int64

### Mathematical Methods

In [409]:
marks = pd.Series([80, 90, 70, 60])

In [410]:
marks.sum()

np.int64(300)

In [411]:
marks.mean()

np.float64(75.0)

In [412]:
marks.max()

np.int64(90)

In [413]:
marks.min()

np.int64(60)

In [414]:
marks.count()

np.int64(4)

### Mathematical Operations

In [415]:
numbers = pd.Series([10, 20, 30])

In [416]:
numbers + 5

0    15
1    25
2    35
dtype: int64

In [417]:
numbers * 2

0    20
1    40
2    60
dtype: int64

In [418]:
numbers / 10

0    1.0
1    2.0
2    3.0
dtype: float64

In [419]:
numbers ** 2

0    100
1    400
2    900
dtype: int64

### Check if a Value Exists

In [420]:
numbers = pd.Series([10, 20, 30, 40])

20 in numbers.values

True

### Rename a Series

In [421]:
marks = pd.Series([80, 90, 70], name="Student Marks")

print(marks)

0    80
1    90
2    70
Name: Student Marks, dtype: int64

### Creating a Series

In [422]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [423]:
s = pd.Series((10, 20, 30, 40))

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [424]:
student_marks = {
    "Ali": 85,
    "Sara": 90,
    "John": 78
}

s = pd.Series(student_marks)

print(s)

Ali     85
Sara    90
John    78
dtype: int64

In [425]:
import numpy as np

arr = np.array([10, 20, 30, 40])

s = pd.Series(arr)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

## DataFrame

In [426]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John"],
    "Age": [20, 19, 21],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [427]:
data = [
    ["Ali", 20, 85],
    ["Sara", 19, 90],
    ["John", 21, 78]
]

df = pd.DataFrame(data, columns=["Name", "Age", "Marks"])

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [428]:
data = [
    {"Name": "Ali", "Age": 20},
    {"Name": "Sara", "Age": 19},
    {"Name": "John", "Age": 21}
]

df = pd.DataFrame(data)

print(df)

   Name  Age
0   Ali   20
1  Sara   19
2  John   21

### DataFrame Attributes

In [429]:
df.shape

(3, 2)

In [430]:
df.size

6

In [431]:
df.columns

Index(['Name', 'Age'], dtype='str')

In [432]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [433]:
df.index

RangeIndex(start=0, stop=3, step=1)

### Selecting Data in a DataFrame

In [434]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Age": [20, 19, 21, 22],
    "Marks": [85, 90, 78, 95]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78
3  Emma   22     95

In [435]:
df["Name"]

0     Ali
1    Sara
2    John
3    Emma
Name: Name, dtype: str

In [436]:
df[["Name", "Marks"]]

   Name  Marks
0   Ali     85
1  Sara     90
2  John     78
3  Emma     95

In [437]:
df.loc[0] # by label

Name     Ali
Age       20
Marks     85
Name: 0, dtype: object

In [438]:
df.loc[0:2] # multiple rows

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [439]:
df.iloc[0] # by location

Name     Ali
Age       20
Marks     85
Name: 0, dtype: object

In [440]:
df.iloc[0:2]

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90

### Filtering Data in Pandas

In [441]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma", "David"],
    "Age": [20, 19, 21, 22, 18],
    "Marks": [85, 90, 78, 95, 65],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks    City
0    Ali   20     85   Delhi
1   Sara   19     90  Mumbai
2   John   21     78   Delhi
3   Emma   22     95    Pune
4  David   18     65  Mumbai

In [442]:
df[df["Marks"] > 80]

   Name  Age  Marks    City
0   Ali   20     85   Delhi
1  Sara   19     90  Mumbai
3  Emma   22     95    Pune

In [443]:
df[df["Age"] < 21]

    Name  Age  Marks    City
0    Ali   20     85   Delhi
1   Sara   19     90  Mumbai
4  David   18     65  Mumbai

In [444]:
df[df["City"] == "Delhi"]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi

In [445]:
df[df["City"] != "Mumbai"]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi
3  Emma   22     95   Pune

In [446]:
df[(df["Marks"] > 80) & (df["Age"] > 20)]

   Name  Age  Marks  City
3  Emma   22     95  Pune

In [447]:
df[(df["City"] == "Delhi") | (df["Marks"] > 90)]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi
3  Emma   22     95   Pune

In [448]:
df[df["City"].isin(["Delhi", "Pune"])]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi
3  Emma   22     95   Pune

In [449]:
df[df["Age"].between(19, 21)]

   Name  Age  Marks    City
0   Ali   20     85   Delhi
1  Sara   19     90  Mumbai
2  John   21     78   Delhi

In [450]:
df[df["Marks"] > 80]["Name"]

0     Ali
1    Sara
3    Emma
Name: Name, dtype: str

In [451]:
df[df["Marks"] > 80][["Name", "Marks"]]

   Name  Marks
0   Ali     85
1  Sara     90
3  Emma     95

### Adding, Updating, Renaming, and Deleting Columns

In [452]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John"],
    "Age": [20, 19, 21],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [453]:
df["City"] = ["Delhi", "Mumbai", "Pune"]

print(df)

   Name  Age  Marks    City
0   Ali   20     85   Delhi
1  Sara   19     90  Mumbai
2  John   21     78    Pune

In [454]:
df["Class"] = "B.Tech"

print(df)

   Name  Age  Marks    City   Class
0   Ali   20     85   Delhi  B.Tech
1  Sara   19     90  Mumbai  B.Tech
2  John   21     78    Pune  B.Tech

In [455]:
df["Updated Marks"] = df["Marks"] + 5

print(df)

   Name  Age  Marks    City   Class  Updated Marks
0   Ali   20     85   Delhi  B.Tech             90
1  Sara   19     90  Mumbai  B.Tech             95
2  John   21     78    Pune  B.Tech             83

In [456]:
df.loc[0, "Marks"] = 88

print(df)

   Name  Age  Marks    City   Class  Updated Marks
0   Ali   20     88   Delhi  B.Tech             90
1  Sara   19     90  Mumbai  B.Tech             95
2  John   21     78    Pune  B.Tech             83

In [457]:
df.rename(columns={"Marks": "Score"})

   Name  Age  Score    City   Class  Updated Marks
0   Ali   20     88   Delhi  B.Tech             90
1  Sara   19     90  Mumbai  B.Tech             95
2  John   21     78    Pune  B.Tech             83

In [458]:
df.drop("Age", axis=1)

   Name  Marks    City   Class  Updated Marks
0   Ali     88   Delhi  B.Tech             90
1  Sara     90  Mumbai  B.Tech             95
2  John     78    Pune  B.Tech             83

In [459]:
df.drop("Age", axis=1)

   Name  Marks    City   Class  Updated Marks
0   Ali     88   Delhi  B.Tech             90
1  Sara     90  Mumbai  B.Tech             95
2  John     78    Pune  B.Tech             83

### Handling Missing Values

In [460]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Age": [20, 19, np.nan, 22],
    "Marks": [85, np.nan, 78, 95]
}

df = pd.DataFrame(data)

print(df)

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  19.0    NaN
2  John   NaN   78.0
3  Emma  22.0   95.0

In [461]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False

In [462]:
df.isnull().sum()

Name     0
Age      1
Marks    1
dtype: int64

In [463]:
df.notnull()

   Name    Age  Marks
0  True   True   True
1  True   True  False
2  True  False   True
3  True   True   True

In [464]:
df.fillna(0)

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  19.0    0.0
2  John   0.0   78.0
3  Emma  22.0   95.0

In [465]:
df.fillna(100)

   Name    Age  Marks
0   Ali   20.0   85.0
1  Sara   19.0  100.0
2  John  100.0   78.0
3  Emma   22.0   95.0

In [466]:
df["Marks"] = df["Marks"].fillna(0)

In [467]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [468]:
df["Marks"] = df["Marks"].fillna(df["Marks"].median())

In [469]:
df.dropna()

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  19.0    0.0
3  Emma  22.0   95.0

In [470]:
df.dropna(how="all")

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  19.0    0.0
2  John   NaN   78.0
3  Emma  22.0   95.0

In [471]:
df.dropna(axis=1)

   Name  Marks
0   Ali   85.0
1  Sara    0.0
2  John   78.0
3  Emma   95.0

In [472]:
df = df.fillna(0)

In [473]:
df.fillna(0, inplace=True)

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  19.0    0.0
2  John   0.0   78.0
3  Emma  22.0   95.0

In [474]:
df.dropna(inplace=True)

### Sorting Data in Pandas

In [475]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Age": [20, 19, 21, 22],
    "Marks": [85, 90, 78, 95]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78
3  Emma   22     95

In [476]:
df.sort_values("Marks")

   Name  Age  Marks
2  John   21     78
0   Ali   20     85
1  Sara   19     90
3  Emma   22     95

In [477]:
df.sort_values("Marks", ascending=True)

   Name  Age  Marks
2  John   21     78
0   Ali   20     85
1  Sara   19     90
3  Emma   22     95

In [478]:
df.sort_values("Marks", ascending=False)

   Name  Age  Marks
3  Emma   22     95
1  Sara   19     90
0   Ali   20     85
2  John   21     78

In [479]:
df.sort_values("Age")

   Name  Age  Marks
1  Sara   19     90
0   Ali   20     85
2  John   21     78
3  Emma   22     95

In [480]:
df.sort_values("Name")

   Name  Age  Marks
0   Ali   20     85
3  Emma   22     95
2  John   21     78
1  Sara   19     90

### GroupBy

In [481]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma", "David"],
    "City": ["Delhi", "Delhi", "Mumbai", "Mumbai", "Pune"],
    "Marks": [85, 90, 78, 95, 88]
}

df = pd.DataFrame(data)

print(df)

    Name    City  Marks
0    Ali   Delhi     85
1   Sara   Delhi     90
2   John  Mumbai     78
3   Emma  Mumbai     95
4  David    Pune     88

In [482]:
df.groupby("City")

In [483]:
df.groupby("City")["Marks"].mean()

City
Delhi     87.5
Mumbai    86.5
Pune      88.0
Name: Marks, dtype: float64

In [484]:
df.groupby("City")["Marks"].sum()

City
Delhi     175
Mumbai    173
Pune       88
Name: Marks, dtype: int64

In [485]:
df.groupby("City")["Name"].count()

City
Delhi     2
Mumbai    2
Pune      1
Name: Name, dtype: int64

In [486]:
df.groupby("City")["Marks"].max()

City
Delhi     90
Mumbai    95
Pune      88
Name: Marks, dtype: int64

In [487]:
df.groupby("City")["Marks"].min()

City
Delhi     85
Mumbai    78
Pune      88
Name: Marks, dtype: int64

In [488]:
df.groupby("City")["Marks"].agg(["mean", "sum", "max", "min", "count"])

        mean  sum  max  min  count
City
Delhi   87.5  175   90   85      2
Mumbai  86.5  173   95   78      2
Pune    88.0   88   88   88      1

In [489]:
df.groupby("City")["Marks"].mean().reset_index()

     City  Marks
0   Delhi   87.5
1  Mumbai   86.5
2    Pune   88.0

### Merge, Join, and Concat

In [490]:
import pandas as pd

students = pd.DataFrame({
    "Student_ID": [101, 102, 103],
    "Name": ["Ali", "Sara", "John"]
})

print(students)

   Student_ID  Name
0         101   Ali
1         102  Sara
2         103  John

In [491]:
marks = pd.DataFrame({
    "Student_ID": [101, 102, 103],
    "Marks": [85, 90, 78]
})

print(marks)

   Student_ID  Marks
0         101     85
1         102     90
2         103     78

In [492]:
result = pd.merge(students, marks, on="Student_ID")

print(result)

   Student_ID  Name  Marks
0         101   Ali     85
1         102  Sara     90
2         103  John     78

In [493]:
pd.merge(students, marks, on="Student_ID")

   Student_ID  Name  Marks
0         101   Ali     85
1         102  Sara     90
2         103  John     78

In [494]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how="left"
)

   Student_ID  Name  Marks
0         101   Ali     85
1         102  Sara     90
2         103  John     78

In [495]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how="right"
)

   Student_ID  Name  Marks
0         101   Ali     85
1         102  Sara     90
2         103  John     78

In [496]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how="outer"
)

   Student_ID  Name  Marks
0         101   Ali     85
1         102  Sara     90
2         103  John     78

In [497]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"]
})

df2 = pd.DataFrame({
    "Name": ["John", "Emma"]
})

pd.concat([df1, df2])

   Name
0   Ali
1  Sara
0  John
1  Emma

In [498]:
pd.concat([df1, df2], axis=1)

   Name  Name
0   Ali  John
1  Sara  Emma

### String Functions (.str Accessor)

In [499]:
import pandas as pd

data = {
    "Name": ["ali", "SARA", "John", "emma"],
    "City": ["delhi", "MUMBAI", "Pune", "CHENNAI"],
    "Email": [
        "ali@gmail.com",
        "sara@yahoo.com",
        "john@gmail.com",
        "emma@hotmail.com"
    ]
}

df = pd.DataFrame(data)

print(df)

   Name     City             Email
0   ali    delhi     ali@gmail.com
1  SARA   MUMBAI    sara@yahoo.com
2  John     Pune    john@gmail.com
3  emma  CHENNAI  emma@hotmail.com

In [500]:
df["Name"].str.upper()

0     ALI
1    SARA
2    JOHN
3    EMMA
Name: Name, dtype: str

In [501]:
df["City"].str.lower()

0      delhi
1     mumbai
2       pune
3    chennai
Name: City, dtype: str

In [502]:
df["Name"].str.title()

0     Ali
1    Sara
2    John
3    Emma
Name: Name, dtype: str

In [503]:
df["Name"].str.len()

0    3
1    4
2    4
3    4
Name: Name, dtype: int64

In [504]:
df["Name"].str.contains("a")

0     True
1    False
2    False
3     True
Name: Name, dtype: bool

In [505]:
df["Name"].str.contains("a", case=False)

0     True
1     True
2    False
3     True
Name: Name, dtype: bool

In [506]:
df["Email"].str.startswith("ali")

0     True
1    False
2    False
3    False
Name: Email, dtype: bool

In [507]:
df["Email"].str.endswith("gmail.com")

0     True
1    False
2     True
3    False
Name: Email, dtype: bool

In [508]:
df[df["Email"].str.endswith("gmail.com")]

   Name   City           Email
0   ali  delhi   ali@gmail.com
2  John   Pune  john@gmail.com

In [509]:
df["City"].str.replace("delhi", "Delhi")

0      Delhi
1     MUMBAI
2       Pune
3    CHENNAI
Name: City, dtype: str

In [510]:
df["City"] = df["City"].str.replace("delhi", "Delhi")

In [511]:
df["Name"].str.slice(0, 3)

0    ali
1    SAR
2    Joh
3    emm
Name: Name, dtype: str

### Date and Time in Pandas

In [512]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Order_Date": [
        "2026-07-20",
        "2026-08-15",
        "2025-12-10",
        "2026-01-05"
    ]
}

df = pd.DataFrame(data)

print(df)

   Name  Order_Date
0   Ali  2026-07-20
1  Sara  2026-08-15
2  John  2025-12-10
3  Emma  2026-01-05

In [513]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [514]:
df["Order_Date"].dt.year

0    2026
1    2026
2    2025
3    2026
Name: Order_Date, dtype: int32

In [515]:
df["Order_Date"].dt.month

0     7
1     8
2    12
3     1
Name: Order_Date, dtype: int32

In [516]:
df["Order_Date"].dt.day

0    20
1    15
2    10
3     5
Name: Order_Date, dtype: int32

In [517]:
df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month
df["Day"] = df["Order_Date"].dt.day

In [518]:
df["Order_Date"].dt.day_name()

0       Monday
1     Saturday
2    Wednesday
3       Monday
Name: Order_Date, dtype: str

In [519]:
df["Order_Date"].dt.month_name()

0        July
1      August
2    December
3     January
Name: Order_Date, dtype: str

In [520]:
df[df["Order_Date"].dt.year == 2026]

   Name Order_Date  Year  Month  Day
0   Ali 2026-07-20  2026      7   20
1  Sara 2026-08-15  2026      8   15
3  Emma 2026-01-05  2026      1    5

In [521]:
df[df["Order_Date"].dt.month == 7]

  Name Order_Date  Year  Month  Day
0  Ali 2026-07-20  2026      7   20

In [522]:
pd.Timestamp.now()

Timestamp('2026-07-30 20:21:44.496336')

In [523]:
pd.Timestamp.today().date()

datetime.date(2026, 7, 30)

In [524]:
import pandas as pd

start = pd.to_datetime("2026-07-01")
end = pd.to_datetime("2026-07-15")

In [525]:
end - start

Timedelta('14 days 00:00:00')

In [526]:
date = pd.to_datetime("2026-07-20")

date + pd.Timedelta(days=5)

Timestamp('2026-07-25 00:00:00')

In [527]:
date - pd.Timedelta(days=10)

Timestamp('2026-07-10 00:00:00')

### map(), apply(), and lambda

In [528]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Marks": [85, 90, 78, 95]
}

df = pd.DataFrame(data)

print(df)

   Name  Marks
0   Ali     85
1  Sara     90
2  John     78
3  Emma     95

In [529]:
df["Marks"].map(lambda x: x + 5)

0     90
1     95
2     83
3    100
Name: Marks, dtype: int64

In [530]:
df["Marks"].map(lambda x: x * 2)

0    170
1    180
2    156
3    190
Name: Marks, dtype: int64

In [531]:
df["Marks"].map(lambda x: "Pass" if x >= 80 else "Fail")

0    Pass
1    Pass
2    Fail
3    Pass
Name: Marks, dtype: str

In [532]:
df["Marks"].apply(lambda x: x + 10)

0     95
1    100
2     88
3    105
Name: Marks, dtype: int64

In [533]:
df["Name"].apply(len)

0    3
1    4
2    4
3    4
Name: Name, dtype: int64

### Pivot Tables (pivot_table())

In [534]:
import pandas as pd

data = {
    "City": ["Delhi", "Delhi", "Mumbai", "Mumbai", "Delhi"],
    "Product": ["Laptop", "Mobile", "Laptop", "Mobile", "Mobile"],
    "Sales": [50000, 20000, 55000, 18000, 15000]
}

df = pd.DataFrame(data)

print(df)

     City Product  Sales
0   Delhi  Laptop  50000
1   Delhi  Mobile  20000
2  Mumbai  Laptop  55000
3  Mumbai  Mobile  18000
4   Delhi  Mobile  15000

In [535]:
pd.pivot_table(
    df,
    index="City",
    values="Sales"
)

               Sales
City
Delhi   28333.333333
Mumbai  36500.000000

In [536]:
pd.pivot_table(
    df,
    index="City",
    values="Sales",
    aggfunc="sum"
)

        Sales
City
Delhi   85000
Mumbai  73000

In [537]:
pd.pivot_table(
    df,
    index="City",
    values="Sales",
    aggfunc="max"
)

        Sales
City
Delhi   50000
Mumbai  55000

In [538]:
pd.pivot_table(
    df,
    index="City",
    values="Sales",
    aggfunc=["sum", "mean", "max"]
)

          sum          mean    max
        Sales         Sales  Sales
City
Delhi   85000  28333.333333  50000
Mumbai  73000  36500.000000  55000

In [539]:
pd.pivot_table(
    df,
    index="City",
    columns="Product",
    values="Sales",
    aggfunc="sum"
)

Product  Laptop  Mobile
City
Delhi     50000   35000
Mumbai    55000   18000

### pd.crosstab()

In [540]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma", "David", "Aisha"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
    "City": ["Delhi", "Delhi", "Mumbai", "Mumbai", "Delhi", "Mumbai"]
}

df = pd.DataFrame(data)

print(df)

    Name  Gender    City
0    Ali    Male   Delhi
1   Sara  Female   Delhi
2   John    Male  Mumbai
3   Emma  Female  Mumbai
4  David    Male   Delhi
5  Aisha  Female  Mumbai

In [541]:
pd.crosstab(df["City"], df["Gender"])

Gender  Female  Male
City
Delhi        1     2
Mumbai       2     1

In [542]:
pd.crosstab(
    df["City"],
    df["Gender"],
    margins=True
)

Gender  Female  Male  All
City
Delhi        1     2    3
Mumbai       2     1    3
All          3     3    6

In [543]:
pd.crosstab(
    df["City"],
    df["Gender"],
    normalize=True
)

Gender    Female      Male
City
Delhi   0.166667  0.333333
Mumbai  0.333333  0.166667

In [544]:
pd.crosstab(
    df["City"],
    df["Gender"],
    normalize="index"
)

Gender    Female      Male
City
Delhi   0.333333  0.666667
Mumbai  0.666667  0.333333

In [545]:
pd.crosstab(
    df["City"],
    df["Gender"],
    normalize="columns"
)

Gender    Female      Male
City
Delhi   0.333333  0.666667
Mumbai  0.666667  0.333333

### duplicated() and drop_duplicates()

In [546]:
import pandas as pd

data = {
    "ID": [101,102,102,103,104,104],
    "Name": ["Ali","Sara","Sara","John","Emma","Emma"]
}

df = pd.DataFrame(data)

print(df)

    ID  Name
0  101   Ali
1  102  Sara
2  102  Sara
3  103  John
4  104  Emma
5  104  Emma

In [547]:
df[df.duplicated()]

    ID  Name
2  102  Sara
5  104  Emma

In [548]:
df.drop_duplicates()

    ID  Name
0  101   Ali
1  102  Sara
3  103  John
4  104  Emma

In [549]:
df.drop_duplicates(inplace=True)

In [550]:
df.duplicated(subset="Name")

0    False
1    False
3    False
4    False
dtype: bool

In [551]:
df.drop_duplicates(subset="Name")

    ID  Name
0  101   Ali
1  102  Sara
3  103  John
4  104  Emma

In [552]:
df.drop_duplicates(keep="last")

    ID  Name
0  101   Ali
1  102  Sara
3  103  John
4  104  Emma

In [553]:
df.drop_duplicates(keep=False)

    ID  Name
0  101   Ali
1  102  Sara
3  103  John
4  104  Emma

In [554]:
df.duplicated().sum()

np.int64(0)

### unique(), nunique(), and value_counts()

In [556]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma", "David", "Aisha"],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Delhi", "Mumbai"],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT", "CSE"]
}

df = pd.DataFrame(data)

print(df)

    Name    City Department
0    Ali   Delhi        CSE
1   Sara  Mumbai         IT
2   John   Delhi        CSE
3   Emma    Pune        ECE
4  David   Delhi         IT
5  Aisha  Mumbai        CSE

In [557]:
df["City"].unique()

<StringArray>
['Delhi', 'Mumbai', 'Pune']
Length: 3, dtype: str

In [558]:
df["Department"].unique()

<StringArray>
['CSE', 'IT', 'ECE']
Length: 3, dtype: str

In [559]:
df["City"].nunique()

3

In [560]:
df["Department"].nunique()

3

In [561]:
df["City"].value_counts()

City
Delhi     3
Mumbai    2
Pune      1
Name: count, dtype: int64

In [562]:
df["Department"].value_counts()

Department
CSE    3
IT     2
ECE    1
Name: count, dtype: int64

In [563]:
df["City"].value_counts(sort=False)

City
Delhi     3
Mumbai    2
Pune      1
Name: count, dtype: int64

In [564]:
df["City"].value_counts(normalize=True)

City
Delhi     0.500000
Mumbai    0.333333
Pune      0.166667
Name: proportion, dtype: float64

In [565]:
df["City"].value_counts(dropna=False)

City
Delhi     3
Mumbai    2
Pune      1
Name: count, dtype: int64

### Window Functions

In [566]:
import pandas as pd

data = {
    "Day": [1,2,3,4,5,6,7],
    "Sales": [100,120,90,150,180,170,200]
}

df = pd.DataFrame(data)

print(df)

   Day  Sales
0    1    100
1    2    120
2    3     90
3    4    150
4    5    180
5    6    170
6    7    200

In [567]:
df["Sales"].rolling(window=3).mean()

0           NaN
1           NaN
2    103.333333
3    120.000000
4    140.000000
5    166.666667
6    183.333333
Name: Sales, dtype: float64

In [568]:
df["Sales"].rolling(3).sum()

0      NaN
1      NaN
2    310.0
3    360.0
4    420.0
5    500.0
6    550.0
Name: Sales, dtype: float64

In [569]:
df["Sales"].rolling(3).max()

0      NaN
1      NaN
2    120.0
3    150.0
4    180.0
5    180.0
6    200.0
Name: Sales, dtype: float64

In [570]:
df["Sales"].rolling(3).min()

0      NaN
1      NaN
2     90.0
3     90.0
4     90.0
5    150.0
6    170.0
Name: Sales, dtype: float64

In [571]:
df["Sales"].rolling(3).count()

0    NaN
1    NaN
2    3.0
3    3.0
4    3.0
5    3.0
6    3.0
Name: Sales, dtype: float64

In [572]:
df["Sales"].expanding().sum()

0     100.0
1     220.0
2     310.0
3     460.0
4     640.0
5     810.0
6    1010.0
Name: Sales, dtype: float64

In [573]:
df["Sales"].expanding().mean()

0    100.000000
1    110.000000
2    103.333333
3    115.000000
4    128.000000
5    135.000000
6    144.285714
Name: Sales, dtype: float64

In [574]:
df["Sales"].shift(1)

0      NaN
1    100.0
2    120.0
3     90.0
4    150.0
5    180.0
6    170.0
Name: Sales, dtype: float64

In [575]:
df["Yesterday"] = df["Sales"].shift(1)

In [576]:
df["Difference"] = (
    df["Sales"] -
    df["Sales"].shift(1)
)

In [577]:
df["Sales"].shift(-1)

0    120.0
1     90.0
2    150.0
3    180.0
4    170.0
5    200.0
6      NaN
Name: Sales, dtype: float64