In [1]:
import sys
print(sys.executable)

c:\Users\majom\OneDrive\Desktop\Python Libraries\Pandas\venv\Scripts\python.exe

In [1]:
import pandas as pd

## Pandas Series

In [2]:
s = pd.Series([10,20,30,40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
fruits = pd.Series(["Apple","Banana","Mango"])
print(fruits)

0     Apple
1    Banana
2     Mango
dtype: str

In [4]:
marks = pd.Series([91.5, 82.0, 76.25])

print(marks)

0    91.50
1    82.00
2    76.25
dtype: float64

In [5]:
passed = pd.Series([True, False, True])

print(passed)

0     True
1    False
2     True
dtype: bool

### Creating a Series with Custom Index

In [6]:
students = pd.Series(
    [85, 90, 78],
    index=["Ali", "Sara", "John"]
)

print(students)

Ali     85
Sara    90
John    78
dtype: int64

### Accessing Values

In [7]:
numbers = pd.Series([10, 20, 30, 40])

print(numbers[0])

10

In [8]:
students = pd.Series(
    [85, 90, 78],
    index=["Ali", "Sara", "John"]
)

print(students["Sara"])

90

### Slicing a Series

In [9]:
numbers = pd.Series([10, 20, 30, 40, 50])

In [10]:
print(numbers[:3])

0    10
1    20
2    30
dtype: int64

### Series Attributes

In [11]:
numbers.dtype

dtype('int64')

In [12]:
numbers.size

5

In [13]:
numbers.shape

(5,)

In [14]:
numbers.values

array([10, 20, 30, 40, 50])

In [15]:
numbers.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
numbers.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [17]:
numbers.head(2)

0    10
1    20
dtype: int64

In [18]:
numbers.tail()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [19]:
numbers.tail(2)

3    40
4    50
dtype: int64

### Mathematical Methods

In [20]:
marks = pd.Series([80, 90, 70, 60])

In [21]:
marks.sum()

np.int64(300)

In [22]:
marks.mean()

np.float64(75.0)

In [23]:
marks.max()

np.int64(90)

In [24]:
marks.min()

np.int64(60)

In [25]:
marks.count()

np.int64(4)

### Mathematical Operations

In [26]:
numbers = pd.Series([10, 20, 30])

In [27]:
numbers + 5

0    15
1    25
2    35
dtype: int64

In [28]:
numbers * 2

0    20
1    40
2    60
dtype: int64

In [29]:
numbers / 10

0    1.0
1    2.0
2    3.0
dtype: float64

In [30]:
numbers ** 2

0    100
1    400
2    900
dtype: int64

### Check if a Value Exists

In [31]:
numbers = pd.Series([10, 20, 30, 40])

20 in numbers.values

True

### Rename a Series

In [32]:
marks = pd.Series([80, 90, 70], name="Student Marks")

print(marks)

0    80
1    90
2    70
Name: Student Marks, dtype: int64

### Creating a Series

In [33]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [34]:
s = pd.Series((10, 20, 30, 40))

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [35]:
student_marks = {
    "Ali": 85,
    "Sara": 90,
    "John": 78
}

s = pd.Series(student_marks)

print(s)

Ali     85
Sara    90
John    78
dtype: int64

In [36]:
import numpy as np

arr = np.array([10, 20, 30, 40])

s = pd.Series(arr)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

## DataFrame

In [37]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John"],
    "Age": [20, 19, 21],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [38]:
data = [
    ["Ali", 20, 85],
    ["Sara", 19, 90],
    ["John", 21, 78]
]

df = pd.DataFrame(data, columns=["Name", "Age", "Marks"])

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [39]:
data = [
    {"Name": "Ali", "Age": 20},
    {"Name": "Sara", "Age": 19},
    {"Name": "John", "Age": 21}
]

df = pd.DataFrame(data)

print(df)

   Name  Age
0   Ali   20
1  Sara   19
2  John   21

### DataFrame Attributes

In [40]:
df.shape

(3, 2)

In [41]:
df.size

6

In [42]:
df.columns

Index(['Name', 'Age'], dtype='str')

In [43]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [44]:
df.index

RangeIndex(start=0, stop=3, step=1)

### Selecting Data in a DataFrame

In [45]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Age": [20, 19, 21, 22],
    "Marks": [85, 90, 78, 95]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78
3  Emma   22     95

In [46]:
df["Name"]

0     Ali
1    Sara
2    John
3    Emma
Name: Name, dtype: str

In [47]:
df[["Name", "Marks"]]

   Name  Marks
0   Ali     85
1  Sara     90
2  John     78
3  Emma     95

In [ ]:
df.loc[0] # by label

Name     Ali
Age       20
Marks     85
Name: 0, dtype: object

In [49]:
df.loc[0:2] # multiple rows

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [50]:
df.iloc[0] # by location

Name     Ali
Age       20
Marks     85
Name: 0, dtype: object

In [51]:
df.iloc[0:2]

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90

### Filtering Data in Pandas

In [52]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma", "David"],
    "Age": [20, 19, 21, 22, 18],
    "Marks": [85, 90, 78, 95, 65],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks    City
0    Ali   20     85   Delhi
1   Sara   19     90  Mumbai
2   John   21     78   Delhi
3   Emma   22     95    Pune
4  David   18     65  Mumbai

In [53]:
df[df["Marks"] > 80]

   Name  Age  Marks    City
0   Ali   20     85   Delhi
1  Sara   19     90  Mumbai
3  Emma   22     95    Pune

In [54]:
df[df["Age"] < 21]

    Name  Age  Marks    City
0    Ali   20     85   Delhi
1   Sara   19     90  Mumbai
4  David   18     65  Mumbai

In [55]:
df[df["City"] == "Delhi"]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi

In [56]:
df[df["City"] != "Mumbai"]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi
3  Emma   22     95   Pune

In [57]:
df[(df["Marks"] > 80) & (df["Age"] > 20)]

   Name  Age  Marks  City
3  Emma   22     95  Pune

In [58]:
df[(df["City"] == "Delhi") | (df["Marks"] > 90)]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi
3  Emma   22     95   Pune

In [59]:
df[df["City"].isin(["Delhi", "Pune"])]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi
3  Emma   22     95   Pune

In [60]:
df[df["Age"].between(19, 21)]

   Name  Age  Marks    City
0   Ali   20     85   Delhi
1  Sara   19     90  Mumbai
2  John   21     78   Delhi

In [61]:
df[df["Marks"] > 80]["Name"]

0     Ali
1    Sara
3    Emma
Name: Name, dtype: str

In [62]:
df[df["Marks"] > 80][["Name", "Marks"]]

   Name  Marks
0   Ali     85
1  Sara     90
3  Emma     95

### Adding, Updating, Renaming, and Deleting Columns

In [63]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John"],
    "Age": [20, 19, 21],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [64]:
df["City"] = ["Delhi", "Mumbai", "Pune"]

print(df)

   Name  Age  Marks    City
0   Ali   20     85   Delhi
1  Sara   19     90  Mumbai
2  John   21     78    Pune

In [65]:
df["Class"] = "B.Tech"

print(df)

   Name  Age  Marks    City   Class
0   Ali   20     85   Delhi  B.Tech
1  Sara   19     90  Mumbai  B.Tech
2  John   21     78    Pune  B.Tech

In [66]:
df["Updated Marks"] = df["Marks"] + 5

print(df)

   Name  Age  Marks    City   Class  Updated Marks
0   Ali   20     85   Delhi  B.Tech             90
1  Sara   19     90  Mumbai  B.Tech             95
2  John   21     78    Pune  B.Tech             83

In [68]:
df.loc[0, "Marks"] = 88

print(df)

   Name  Age  Marks    City   Class  Updated Marks  Double Marks
0   Ali   20     88   Delhi  B.Tech             90           170
1  Sara   19     90  Mumbai  B.Tech             95           180
2  John   21     78    Pune  B.Tech             83           156

In [71]:
df.rename(columns={"Marks": "Score"})

   Name  Age  Score    City   Class  Updated Marks  Double Marks
0   Ali   20     93   Delhi  B.Tech             90           176
1  Sara   19     95  Mumbai  B.Tech             95           180
2  John   21     83    Pune  B.Tech             83           156

In [74]:
df.drop("Age", axis=1)

  Student Name  Score    City   Class  Updated Marks  Double Marks
0          Ali     93   Delhi  B.Tech             90           176
1         Sara     95  Mumbai  B.Tech             95           180
2         John     83    Pune  B.Tech             83           156

In [75]:
df.drop("Age", axis=1)

  Student Name  Score    City   Class  Updated Marks  Double Marks
0          Ali     93   Delhi  B.Tech             90           176
1         Sara     95  Mumbai  B.Tech             95           180
2         John     83    Pune  B.Tech             83           156

### Handling Missing Values