In [1]:
import sys
print(sys.executable)

c:\Users\majom\OneDrive\Desktop\Python Libraries\Pandas\venv\Scripts\python.exe

In [1]:
import pandas as pd

## Pandas Series

In [2]:
s = pd.Series([10,20,30,40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
fruits = pd.Series(["Apple","Banana","Mango"])
print(fruits)

0     Apple
1    Banana
2     Mango
dtype: str

In [4]:
marks = pd.Series([91.5, 82.0, 76.25])

print(marks)

0    91.50
1    82.00
2    76.25
dtype: float64

In [5]:
passed = pd.Series([True, False, True])

print(passed)

0     True
1    False
2     True
dtype: bool

### Creating a Series with Custom Index

In [6]:
students = pd.Series(
    [85, 90, 78],
    index=["Ali", "Sara", "John"]
)

print(students)

Ali     85
Sara    90
John    78
dtype: int64

### Accessing Values

In [7]:
numbers = pd.Series([10, 20, 30, 40])

print(numbers[0])

10

In [8]:
students = pd.Series(
    [85, 90, 78],
    index=["Ali", "Sara", "John"]
)

print(students["Sara"])

90

### Slicing a Series

In [9]:
numbers = pd.Series([10, 20, 30, 40, 50])

In [10]:
print(numbers[:3])

0    10
1    20
2    30
dtype: int64

### Series Attributes

In [11]:
numbers.dtype

dtype('int64')

In [12]:
numbers.size

5

In [13]:
numbers.shape

(5,)

In [14]:
numbers.values

array([10, 20, 30, 40, 50])

In [15]:
numbers.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
numbers.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [17]:
numbers.head(2)

0    10
1    20
dtype: int64

In [18]:
numbers.tail()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [19]:
numbers.tail(2)

3    40
4    50
dtype: int64

### Mathematical Methods

In [20]:
marks = pd.Series([80, 90, 70, 60])

In [21]:
marks.sum()

np.int64(300)

In [22]:
marks.mean()

np.float64(75.0)

In [23]:
marks.max()

np.int64(90)

In [24]:
marks.min()

np.int64(60)

In [25]:
marks.count()

np.int64(4)

### Mathematical Operations

In [26]:
numbers = pd.Series([10, 20, 30])

In [27]:
numbers + 5

0    15
1    25
2    35
dtype: int64

In [28]:
numbers * 2

0    20
1    40
2    60
dtype: int64

In [29]:
numbers / 10

0    1.0
1    2.0
2    3.0
dtype: float64

In [30]:
numbers ** 2

0    100
1    400
2    900
dtype: int64

### Check if a Value Exists

In [31]:
numbers = pd.Series([10, 20, 30, 40])

20 in numbers.values

True

### Rename a Series

In [32]:
marks = pd.Series([80, 90, 70], name="Student Marks")

print(marks)

0    80
1    90
2    70
Name: Student Marks, dtype: int64

### Creating a Series

In [33]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [34]:
s = pd.Series((10, 20, 30, 40))

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [35]:
student_marks = {
    "Ali": 85,
    "Sara": 90,
    "John": 78
}

s = pd.Series(student_marks)

print(s)

Ali     85
Sara    90
John    78
dtype: int64

In [36]:
import numpy as np

arr = np.array([10, 20, 30, 40])

s = pd.Series(arr)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

## DataFrame

In [37]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John"],
    "Age": [20, 19, 21],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [38]:
data = [
    ["Ali", 20, 85],
    ["Sara", 19, 90],
    ["John", 21, 78]
]

df = pd.DataFrame(data, columns=["Name", "Age", "Marks"])

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [39]:
data = [
    {"Name": "Ali", "Age": 20},
    {"Name": "Sara", "Age": 19},
    {"Name": "John", "Age": 21}
]

df = pd.DataFrame(data)

print(df)

   Name  Age
0   Ali   20
1  Sara   19
2  John   21

### DataFrame Attributes

In [40]:
df.shape

(3, 2)

In [41]:
df.size

6

In [42]:
df.columns

Index(['Name', 'Age'], dtype='str')

In [43]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [44]:
df.index

RangeIndex(start=0, stop=3, step=1)

### Selecting Data in a DataFrame

In [45]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Age": [20, 19, 21, 22],
    "Marks": [85, 90, 78, 95]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78
3  Emma   22     95

In [46]:
df["Name"]

0     Ali
1    Sara
2    John
3    Emma
Name: Name, dtype: str

In [47]:
df[["Name", "Marks"]]

   Name  Marks
0   Ali     85
1  Sara     90
2  John     78
3  Emma     95

In [ ]:
df.loc[0] # by label

Name     Ali
Age       20
Marks     85
Name: 0, dtype: object

In [49]:
df.loc[0:2] # multiple rows

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [50]:
df.iloc[0] # by location

Name     Ali
Age       20
Marks     85
Name: 0, dtype: object

In [51]:
df.iloc[0:2]

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90

### Filtering Data in Pandas

In [52]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma", "David"],
    "Age": [20, 19, 21, 22, 18],
    "Marks": [85, 90, 78, 95, 65],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks    City
0    Ali   20     85   Delhi
1   Sara   19     90  Mumbai
2   John   21     78   Delhi
3   Emma   22     95    Pune
4  David   18     65  Mumbai

In [53]:
df[df["Marks"] > 80]

   Name  Age  Marks    City
0   Ali   20     85   Delhi
1  Sara   19     90  Mumbai
3  Emma   22     95    Pune

In [54]:
df[df["Age"] < 21]

    Name  Age  Marks    City
0    Ali   20     85   Delhi
1   Sara   19     90  Mumbai
4  David   18     65  Mumbai

In [55]:
df[df["City"] == "Delhi"]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi

In [56]:
df[df["City"] != "Mumbai"]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi
3  Emma   22     95   Pune

In [57]:
df[(df["Marks"] > 80) & (df["Age"] > 20)]

   Name  Age  Marks  City
3  Emma   22     95  Pune

In [58]:
df[(df["City"] == "Delhi") | (df["Marks"] > 90)]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi
3  Emma   22     95   Pune

In [59]:
df[df["City"].isin(["Delhi", "Pune"])]

   Name  Age  Marks   City
0   Ali   20     85  Delhi
2  John   21     78  Delhi
3  Emma   22     95   Pune

In [60]:
df[df["Age"].between(19, 21)]

   Name  Age  Marks    City
0   Ali   20     85   Delhi
1  Sara   19     90  Mumbai
2  John   21     78   Delhi

In [61]:
df[df["Marks"] > 80]["Name"]

0     Ali
1    Sara
3    Emma
Name: Name, dtype: str

In [62]:
df[df["Marks"] > 80][["Name", "Marks"]]

   Name  Marks
0   Ali     85
1  Sara     90
3  Emma     95

### Adding, Updating, Renaming, and Deleting Columns

In [63]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John"],
    "Age": [20, 19, 21],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78

In [64]:
df["City"] = ["Delhi", "Mumbai", "Pune"]

print(df)

   Name  Age  Marks    City
0   Ali   20     85   Delhi
1  Sara   19     90  Mumbai
2  John   21     78    Pune

In [65]:
df["Class"] = "B.Tech"

print(df)

   Name  Age  Marks    City   Class
0   Ali   20     85   Delhi  B.Tech
1  Sara   19     90  Mumbai  B.Tech
2  John   21     78    Pune  B.Tech

In [66]:
df["Updated Marks"] = df["Marks"] + 5

print(df)

   Name  Age  Marks    City   Class  Updated Marks
0   Ali   20     85   Delhi  B.Tech             90
1  Sara   19     90  Mumbai  B.Tech             95
2  John   21     78    Pune  B.Tech             83

In [68]:
df.loc[0, "Marks"] = 88

print(df)

   Name  Age  Marks    City   Class  Updated Marks  Double Marks
0   Ali   20     88   Delhi  B.Tech             90           170
1  Sara   19     90  Mumbai  B.Tech             95           180
2  John   21     78    Pune  B.Tech             83           156

In [71]:
df.rename(columns={"Marks": "Score"})

   Name  Age  Score    City   Class  Updated Marks  Double Marks
0   Ali   20     93   Delhi  B.Tech             90           176
1  Sara   19     95  Mumbai  B.Tech             95           180
2  John   21     83    Pune  B.Tech             83           156

In [74]:
df.drop("Age", axis=1)

  Student Name  Score    City   Class  Updated Marks  Double Marks
0          Ali     93   Delhi  B.Tech             90           176
1         Sara     95  Mumbai  B.Tech             95           180
2         John     83    Pune  B.Tech             83           156

In [75]:
df.drop("Age", axis=1)

  Student Name  Score    City   Class  Updated Marks  Double Marks
0          Ali     93   Delhi  B.Tech             90           176
1         Sara     95  Mumbai  B.Tech             95           180
2         John     83    Pune  B.Tech             83           156

### Handling Missing Values

In [76]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Age": [20, 19, np.nan, 22],
    "Marks": [85, np.nan, 78, 95]
}

df = pd.DataFrame(data)

print(df)

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  19.0    NaN
2  John   NaN   78.0
3  Emma  22.0   95.0

In [77]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False

In [78]:
df.isnull().sum()

Name     0
Age      1
Marks    1
dtype: int64

In [79]:
df.notnull()

   Name    Age  Marks
0  True   True   True
1  True   True  False
2  True  False   True
3  True   True   True

In [80]:
df.fillna(0)

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  19.0    0.0
2  John   0.0   78.0
3  Emma  22.0   95.0

In [81]:
df.fillna(100)

   Name    Age  Marks
0   Ali   20.0   85.0
1  Sara   19.0  100.0
2  John  100.0   78.0
3  Emma   22.0   95.0

In [82]:
df["Marks"] = df["Marks"].fillna(0)

In [83]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [84]:
df["Marks"] = df["Marks"].fillna(df["Marks"].median())

In [86]:
df.dropna()

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  19.0    0.0
3  Emma  22.0   95.0

In [87]:
df.dropna(how="all")

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  19.0    0.0
2  John   NaN   78.0
3  Emma  22.0   95.0

In [88]:
df.dropna(axis=1)

   Name  Marks
0   Ali   85.0
1  Sara    0.0
2  John   78.0
3  Emma   95.0

In [89]:
df = df.fillna(0)

In [90]:
df.fillna(0, inplace=True)

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  19.0    0.0
2  John   0.0   78.0
3  Emma  22.0   95.0

In [91]:
df.dropna(inplace=True)

### Sorting Data in Pandas

In [92]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Age": [20, 19, 21, 22],
    "Marks": [85, 90, 78, 95]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   19     90
2  John   21     78
3  Emma   22     95

In [93]:
df.sort_values("Marks")

   Name  Age  Marks
2  John   21     78
0   Ali   20     85
1  Sara   19     90
3  Emma   22     95

In [94]:
df.sort_values("Marks", ascending=True)

   Name  Age  Marks
2  John   21     78
0   Ali   20     85
1  Sara   19     90
3  Emma   22     95

In [95]:
df.sort_values("Marks", ascending=False)

   Name  Age  Marks
3  Emma   22     95
1  Sara   19     90
0   Ali   20     85
2  John   21     78

In [96]:
df.sort_values("Age")

   Name  Age  Marks
1  Sara   19     90
0   Ali   20     85
2  John   21     78
3  Emma   22     95

In [97]:
df.sort_values("Name")

   Name  Age  Marks
0   Ali   20     85
3  Emma   22     95
2  John   21     78
1  Sara   19     90

### GroupBy

In [100]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma", "David"],
    "City": ["Delhi", "Delhi", "Mumbai", "Mumbai", "Pune"],
    "Marks": [85, 90, 78, 95, 88]
}

df = pd.DataFrame(data)

print(df)

    Name    City  Marks
0    Ali   Delhi     85
1   Sara   Delhi     90
2   John  Mumbai     78
3   Emma  Mumbai     95
4  David    Pune     88

In [101]:
df.groupby("City")

In [102]:
df.groupby("City")["Marks"].mean()

City
Delhi     87.5
Mumbai    86.5
Pune      88.0
Name: Marks, dtype: float64

In [103]:
df.groupby("City")["Marks"].sum()

City
Delhi     175
Mumbai    173
Pune       88
Name: Marks, dtype: int64

In [104]:
df.groupby("City")["Name"].count()

City
Delhi     2
Mumbai    2
Pune      1
Name: Name, dtype: int64

In [105]:
df.groupby("City")["Marks"].max()

City
Delhi     90
Mumbai    95
Pune      88
Name: Marks, dtype: int64

In [106]:
df.groupby("City")["Marks"].min()

City
Delhi     85
Mumbai    78
Pune      88
Name: Marks, dtype: int64

In [107]:
df.groupby("City")["Marks"].agg(["mean", "sum", "max", "min", "count"])

        mean  sum  max  min  count
City
Delhi   87.5  175   90   85      2
Mumbai  86.5  173   95   78      2
Pune    88.0   88   88   88      1

In [109]:
df.groupby("City")["Marks"].mean().reset_index()

     City  Marks
0   Delhi   87.5
1  Mumbai   86.5
2    Pune   88.0

### Merge, Join, and Concat

In [110]:
import pandas as pd

students = pd.DataFrame({
    "Student_ID": [101, 102, 103],
    "Name": ["Ali", "Sara", "John"]
})

print(students)

   Student_ID  Name
0         101   Ali
1         102  Sara
2         103  John

In [111]:
marks = pd.DataFrame({
    "Student_ID": [101, 102, 103],
    "Marks": [85, 90, 78]
})

print(marks)

   Student_ID  Marks
0         101     85
1         102     90
2         103     78

In [112]:
result = pd.merge(students, marks, on="Student_ID")

print(result)

   Student_ID  Name  Marks
0         101   Ali     85
1         102  Sara     90
2         103  John     78

In [113]:
pd.merge(students, marks, on="Student_ID")

   Student_ID  Name  Marks
0         101   Ali     85
1         102  Sara     90
2         103  John     78

In [114]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how="left"
)

   Student_ID  Name  Marks
0         101   Ali     85
1         102  Sara     90
2         103  John     78

In [115]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how="right"
)

   Student_ID  Name  Marks
0         101   Ali     85
1         102  Sara     90
2         103  John     78

In [116]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how="outer"
)

   Student_ID  Name  Marks
0         101   Ali     85
1         102  Sara     90
2         103  John     78

In [117]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"]
})

df2 = pd.DataFrame({
    "Name": ["John", "Emma"]
})

pd.concat([df1, df2])

   Name
0   Ali
1  Sara
0  John
1  Emma

In [118]:
pd.concat([df1, df2], axis=1)

   Name  Name
0   Ali  John
1  Sara  Emma

### String Functions (.str Accessor)